services:
  whatsapp-microservice:
    build: .
    container_name: whatsapp-microservice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEY=${API_KEY:-test-api-key-change-in-production}
      - WHATSAPP_SESSION_ID=${WHATSAPP_SESSION_ID:-whatsapp-session}
      - WHATSAPP_AUTH_FOLDER=/app/auth
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    volumes:
      - auth_data:/app/auth
      - logs_data:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  auth_data:
    driver: local
  logs_data:
    driver: local