services:
  # Instancia de Ventas
  whatsapp-ventas:
    build: .
    container_name: whatsapp-ventas
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEY=${API_KEY_VENTAS:-ventas-api-key-123}
      - WHATSAPP_SESSION_ID=ventas-session
      - WHATSAPP_AUTH_FOLDER=/app/auth
      - WHATSAPP_INSTANCE_NAME=Ventas
      - WHATSAPP_PHONE_NUMBER=+51987654321
      - LOG_LEVEL=debug
    volumes:
      - ventas_auth:/app/auth
      - ventas_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

  # Instancia de Soporte
  whatsapp-soporte:
    build: .
    container_name: whatsapp-soporte
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEY=${API_KEY_SOPORTE:-soporte-api-key-456}
      - WHATSAPP_SESSION_ID=soporte-session
      - WHATSAPP_AUTH_FOLDER=/app/auth
      - WHATSAPP_INSTANCE_NAME=Soporte
      - WHATSAPP_PHONE_NUMBER=+51987654322
      - LOG_LEVEL=debug
    volumes:
      - soporte_auth:/app/auth
      - soporte_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

  # Instancia de Marketing
  whatsapp-marketing:
    build: .
    container_name: whatsapp-marketing
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEY=${API_KEY_MARKETING:-marketing-api-key-789}
      - WHATSAPP_SESSION_ID=marketing-session
      - WHATSAPP_AUTH_FOLDER=/app/auth
      - WHATSAPP_INSTANCE_NAME=Marketing
      - WHATSAPP_PHONE_NUMBER=+51987654323
      - LOG_LEVEL=debug
    volumes:
      - marketing_auth:/app/auth
      - marketing_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  ventas_auth:
    driver: local
  ventas_logs:
    driver: local
  soporte_auth:
    driver: local
  soporte_logs:
    driver: local
  marketing_auth:
    driver: local
  marketing_logs:
    driver: local